import type { McpClientConfig, PolicyConfig } from '../types.js';
import { dump } from 'js-yaml';

export const DEFAULT_POLICY: PolicyConfig = {
  version: '1',
  mode: 'enforce',
  defaultAction: 'deny',
  rules: [
    {
      id: 'block-shell-execution',
      description: 'Block tools that invoke shell interpreters directly',
      target: 'command',
      match: 'pattern',
      values: [
        '^bash$',
        '^sh$',
        '^zsh$',
        '^cmd$',
        '^powershell$',
        '^pwsh$',
        '^/bin/bash$',
        '^/bin/sh$',
        '^/bin/zsh$',
        '^/usr/bin/bash$',
        '^/usr/bin/sh$',
        '^/usr/bin/zsh$',
        '\\bbash\\s+-c\\b',
        '\\bsh\\s+-c\\b',
        '\\bzsh\\s+-c\\b',
        '\\bcmd\\.exe\\s+/c\\b',
        '\\bpowershell\\s+-Command\\b',
        '\\bpwsh\\s+-Command\\b',
      ],
      action: 'deny',
    },
    {
      id: 'block-sensitive-paths',
      description: 'Block filesystem writes to sensitive system and configuration paths',
      target: 'file',
      match: 'pattern',
      values: [
        '^/etc(/|$)',
        '^/root(/|$)',
        '^/home/[^/]+/\\.ssh(/|$)',
        '^/home/[^/]+/\\.aws(/|$)',
        '^~/\\.ssh(/|$)',
        '^~/\\.aws(/|$)',
        '^/var(/|$)',
        '^/usr(/|$)',
        '^/System(/|$)',
        '^C:\\\\Windows',
        '^C:\\\\Program Files',
        '^%SystemRoot%',
        '^%ProgramFiles%',
      ],
      action: 'deny',
    },
    {
      id: 'block-credential-access',
      description: 'Block tools whose descriptions indicate credential or secret access',
      target: 'command',
      match: 'contains',
      values: ['password', 'secret', 'token', 'api_key', 'credential', 'private key'],
      action: 'deny',
    },
    {
      id: 'block-private-network',
      description: 'Block outbound network requests to private and loopback address ranges',
      target: 'network',
      match: 'pattern',
      values: [
        '^https?://10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}',
        '^https?://172\\.(1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}',
        '^https?://192\\.168\\.\\d{1,3}\\.\\d{1,3}',
        '^https?://127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}',
        '^https?://localhost',
        '^https?://\\[::1\\]',
        '\\b10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b',
        '\\b172\\.(1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}\\b',
        '\\b192\\.168\\.\\d{1,3}\\.\\d{1,3}\\b',
        '\\b127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b',
      ],
      action: 'deny',
    },
    {
      id: 'block-process-execution',
      description: 'Block tools that spawn child processes or evaluate arbitrary code',
      target: 'process',
      match: 'pattern',
      values: [
        '\\bexec\\b',
        '\\bspawn\\b',
        '\\bfork\\b',
        '\\bsystem\\b',
        '\\beval\\b',
        '\\bchild_process\\b',
        '\\bexecSync\\b',
        '\\bspawnSync\\b',
        '\\bexecFile\\b',
        '\\bexecFileSync\\b',
      ],
      action: 'deny',
    },
  ],
  allowlist: {
    tools: [],
    paths: [],
    hosts: [],
    envVars: [],
  },
};

export function generateDefaultPolicy(configs: McpClientConfig[], mode: string = "audit"): PolicyConfig {
  const allTools = new Set<string>();
  const allHosts = new Set<string>();

  for (const config of configs) {
    for (const server of config.servers) {
      allTools.add(server.name);
      if (server.url) {
        try {
          const host = new URL(server.url).hostname;
          allHosts.add(host);
        } catch {
          // ignore invalid URLs
        }
      }
    }
  }

  return {
    version: "0.1.0",
    mode: mode as "audit" | "enforce",
    defaultAction: "deny",
    rules: DEFAULT_POLICY.rules,
    allowlist: {
      tools: [...allTools],
      paths: [],
      hosts: [...allHosts],
      envVars: [],
    },
  };
}

export function generateDefaultPolicyFile(): string {
  const policyForYaml = {
    version: DEFAULT_POLICY.version,
    mode: DEFAULT_POLICY.mode,
    defaultAction: DEFAULT_POLICY.defaultAction,
    rules: DEFAULT_POLICY.rules.map((rule) => ({
      id: rule.id,
      description: rule.description,
      target: rule.target,
      match: rule.match,
      values: rule.values,
      action: rule.action,
    })),
    allowlist: DEFAULT_POLICY.allowlist,
  };

  return [
    '# mcp-seatbelt default policy',
    '# Generated by mcp-seatbelt --policy-defaults',
    '#',
    '# mode: audit | enforce',
    '#   audit   - log policy violations but allow all calls',
    '#   enforce - block denied calls and warn on uncertain calls',
    '#',
    '# defaultAction: allow | deny',
    '#   allow - permit calls that do not match any rule',
    '#   deny  - block calls that do not match any rule (recommended)',
    '#',
    '# Rules target: command | file | network | env | process',
    '# Rules match:  exact | pattern | contains',
    '# Rules action: allow | deny | warn',
    '',
    dump(policyForYaml, { indent: 2, lineWidth: -1, noRefs: true }),
  ].join('\n');
}
